qiuwenbaike/QiuwenGadgets

src/Collapsible/Collapsible.less
src/Ding/Ding.less
src/Edit0/Edit0.less
src/FloatTOC/FloatTOC.less
src/FoldRef/FoldRef.less
src/GeoLocationReader/GeoLocationReader.less
src/Mainpage-ChineseNewYear/Mainpage-ChineseNewYear.less
src/Mainpage/Mainpage.less
src/MarkBlocked/MarkBlocked.less
src/MarkRights-Userpage/MarkRights-Userpage.less
src/NavFrame/NavFrame.less
src/NavboxCSS/NavboxCSS.css
src/ProveIt/ProveIt.less
src/ScrollUpButton/ScrollUpButton.less
src/ShortURL/ShortURL.less
src/SiteCommon/modules/columns.less
src/SiteCommon/modules/filePage.less
src/SiteCommon/modules/mbox.less
src/SiteCommon/modules/newArticleText.less
src/SiteCommon/modules/noArticleText.less
src/SiteCommon/modules/print.less
src/SiteCommon/modules/uploadText.less
src/WhoIsActive/WhoIsActive.less
src/select2/select2.less

all vendor prefixes will be automatically inserted during the build process

refactor: remove css/less vendor prefix

---

.eslintignore
.prettierignore

all removed rules are enabled by default

build: remove unnecessary ignore rules

---

.editorconfig

style(EditorConfig): set special rules for SVG files

---

src/FloatTOC/modules/core.ts
src/Report/modules/addButton.ts
src/ScrollUpButton/modules/core.ts
src/SmoothTOC/modules/core.ts
src/util.ts

changeOpacityWhenMouseEnterOrLeave
scrollTop

refactor(util): add common methods

---

src/AjaxLogin/modules/core.ts

`lastToastifyInstance` is not defined

fix(AjaxLogin): reference error

---

.browserslistrc
.stylelintrc

switch from modern support to basic support

build: update browserslist and stylelint rules

---

src/AjaxLogin/modules/core.ts

fix(AjaxLogin): cannot close window

---

src/ToolsRedirect/modules/messages.js

refactor(ToolsRedirect): update messages

---

src/AccessKeyCheatsheet/modules/util/generateAccessKeysTableWithOpener.ts
src/SiteCommon_JS/modules/tippy.ts

to remove unnecessary text in the title attribute

refactor: update the regular expression

---

src/AjaxLogin/modules/core.ts
src/AjaxLogin/modules/util/checkValid.ts
src/ConfirmLogout/modules/addListener.ts

move the "node" and "text" properties to the front for easier reading

refactor: adjust the order of properties

---

src/UserRightsManager/modules/core.js

when the page has the same username

fix(UserRightsManager): edit the incorrect section

---

.browserslistrc
package.json
pnpm-lock.yaml

build: remove unused packages

---

src/DisamAssist/modules/core.js
src/HotCat/HotCat.js
src/Navigation_popups/modules/core.js
src/SpecialWikitext/SpecialWikitext.ts
src/TextSpacing/modules/spacing.ts
src/morebits/morebits.js

fix: eslint errors

---

src/AdvancedSiteNotices-pagestyles/AdvancedSiteNotices-pagestyles.less

fix(ASN): the element height should increase with the number of text

---

src/AdvancedSiteNotices/modules/i18n.ts
src/AdvancedSiteNotices/modules/util/matchCriteria.ts

chore(ASN): improve translation

refactor(ASN): capture exceptions that may be thrown by `mw.Uri.decode`

---

dist/VerifyToEdit/VerifyToEdit.js
dist/definition.txt
src/VerifyToEdit/LICENSE
src/VerifyToEdit/VerifyToEdit.ts
src/VerifyToEdit/definition.json
src/VerifyToEdit/modules/i18n.ts
src/VerifyToEdit/modules/initDialog.ts
src/VerifyToEdit/modules/initWindowManager.ts
src/VerifyToEdit/modules/util/generateMessageDialogProperty.ts

> VerifyToEdit is copied from LoginToEdit

feat(add): add VerifyToEdit

---

src/ToolsRedirect-courtesy-and-art-names/modules/courtesy-and-art-names.ts

* optimize code
* textContent → textContent2

fix(ToolRedirect): fix typo

---

dist/definition.txt
src/EditConflict/definition.json
src/Edittools-customizeToolbar/definition.json
src/Edittools-delh/definition.json
src/Edittools-refToolbar/definition.json
src/Edittools-vector/definition.json
src/Edittools-vplus/definition.json
src/Wikicache/definition.json

* See https://www.mediawiki.org/wiki/Extension:Gadgets#Options

build: remove wrong option 'submit'

---

dist/definition.txt
src/RightTopicons/definition.json
src/ShortURL/definition.json
src/Tippy/definition.json
src/Toastify/definition.json

* turn off ShortURL by default
* update desc

build: update dist; update settings

---

pnpm-lock.yaml

Reverts qiuwenbaike/QiuwenGadgets#1599

Revert "build(deps): bump nanoid from 3.3.7 to 3.3.8"
